# tasks file for preinstall
   
   - name: update system CentOS
     yum:  name="*" state=latest  update_cache=yes
     when: ansible_distribution == "CentOS"
  
   - name: install ntp
     yum: name=ntp state=latest
   - service: name=ntpd enabled=yes
   - service: name=ntpd state=restarted

   - name: install epel
     yum: name=epel-release state=present

   - name: Install 
     yum: 
       name:
         - ntp 
         - screen 
         - libselinux-python
         - bzip2
         - vim
       state: latest

   - name: Put SELinux in permissive mode, logging actions that would be blocked.
     ansible.posix.selinux:
       policy: targeted
       state: permissive

   - name: symlink set timezone Kyiv 
     file: src=/usr/share/zoneinfo/Europe/Kiev dest=/etc/localtime state=link force=yes

   - name: remove firewalld for CentOS 7
     yum: name=firewalld state=removed
     when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7")

   - name: install iptables for CentOS 7
     yum: name=iptables-services state=latest
     when: (ansible_distribution == "CentOS" and ansible_distribution_major_version >= "7")

   - service: name=iptables enabled=yes
     when: ansible_distribution == "CentOS"

   - name: add template iptables
     template: src=iptables.j2 dest=/etc/sysconfig/iptables

   - service: name=iptables state=restarted

   - name: add to host 
     lineinfile:
       path: /etc/hosts
       line: "{{ item }}"
     with_items:
       - "10.0.34.3  test-centos7-node1"
       - "10.0.34.4  test-centos7-node2"
       - "10.0.34.2  test-centos7-node3"

