---
- name: python2-pip
  yum:
    name: python2-pip
    state: latest

- pip:
    name: 
      - docker-py 
      - pyyaml
      - jsondiff

- name: create swarm directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/swarm_data/gitlab/data"
    - "/home/swarm_data/gitlab/logs"
    - "/home/swarm_data/gitlab/config"
    - "/opt/gitlap_deploy"


- name: Copy docker-compose file with owner and permissions
  copy:
    src: files/
    dest: "/opt/gitlap_deploy"
    owner: root
    group: root
    mode: '0640'

- name: Deploy stack from a compose file
  community.general.docker_stack:
    state: present
    name: gitlab
    compose:
      - "/opt/gitlap_deploy/docker-compose.yml"
